CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY, 
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(254) UNIQUE NOT NULL,
  phone_number VARCHAR(15) UNIQUE DEFAULT NULL,
  password CHAR(60) NOT NULL,
  role ENUM('customer', 'seller', 'admin') NOT NULL DEFAULT 'customer',
  status ENUM('active', 'deleted', 'pending') NOT NULL DEFAULT 'pending',
  avatar_url VARCHAR(255) DEFAULT NULL,
  otp CHAR(6) DEFAULT NULL,
  otp_expired TIMESTAMP NULL DEFAULT NULL,
  token VARCHAR(64) UNIQUE DEFAULT NULL,
  token_expired TIMESTAMP NULL DEFAULT NULL,
  last_login TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;