CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY, 
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(254) UNIQUE NOT NULL,
  phone_number VARCHAR(15) UNIQUE DEFAULT NULL,
  password CHAR(60) NOT NULL,
  role ENUM('customer', 'seller', 'admin') NOT NULL DEFAULT 'customer',
  status ENUM('active', 'deleted', 'pending') NOT NULL DEFAULT 'pending',
  avatar VARCHAR(255) DEFAULT NULL,
  otp CHAR(6) DEFAULT NULL,
  token VARCHAR(255) UNIQUE DEFAULT NULL, 
  last_login DATETIME NULL DEFAULT NULL,
  expired_at DATETIME NULL DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;